# Generated by Django 3.0.2 on 2020-01-22 11:35

from django.db import migrations, models
import django.db.models.deletion
import fashion.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fashion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to=fashion.models.upload, verbose_name='Image')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Fashion',
                'verbose_name_plural': 'Fashions',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=50, null=True, verbose_name='User')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('image2', models.ImageField(blank=True, null=True, upload_to=fashion.models.upload_image, verbose_name='Image')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fashion.Fashion', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
