# Generated by Django 3.0.2 on 2020-01-22 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fashion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
