# Generated by Django 3.0.2 on 2020-01-23 13:32

from django.db import migrations, models
import fashion.models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0002_auto_20200122_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=fashion.models.upload_image, verbose_name='Image1'),
        ),
    ]
